version: 2

project_name: oro

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: oro
    main: ./cmd/oro
    binary: oro
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: checksums.txt

nfpms:
  - id: oro
    ids:
      - oro
    formats:
      - deb
      - rpm
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Wilson Santos <contato@wilsonsantos.net>
    description: CLI em Go (oro) para criação, inicialização e padronização de projetos de software.

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

release:
  disable: true
